version: "3"

services:
  db:
    image: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_PASSWORD: rocketpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: rocketdb

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:rocketpassword@localhost/rocketdb
      DB_USER: changeToEnv
      DB_NAME: changeToEnv
      DB_PASSWORD: changeToEnv
      DB_HOST: changeToEnv
      ROCKET_ENV: production
    healthcheck:
      test: curl --fail http://127.0.0.1:6666/health || exit 1
      interval: 20s
      timeout: 5s
      retries: 5

    depends_on:
      db:
        condition: service_healthy

    expose:
      - 9999
    ports:
      - "9999:9999"