[workspace]
[package]
version = "0.1.0"
name = "sp1-script"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/t0rs/sp1-privacy.git" }
sp1-core = { git = "https://github.com/t0rs/sp1-privacy.git" }
serde_json = "1.0"
