# Generated by Django 4.2.4 on 2024-03-11 13:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    users.models.LowercaseCharField(max_length=20, unique=True),
                ),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
