name: Docker Image CI

on:
  push:
    branches: ['main']
    paths: ['backend/**']

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        working-directory: backend
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build . --tag ghcr.io/$REPO_OWNER_LOWERCASE/ttm4905/backend-image:latest
          docker push ghcr.io/$REPO_OWNER_LOWERCASE/ttm4905/backend-image:latest
          
